---
- project:
    templates:
      - openstack-python3-xena-jobs
      - openstack-python3-xena-jobs-arm64
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - periodic-stable-jobs
